- type: job
  id: ChiefEngineer
  name: job-name-ce
  description: job-description-ce
  playTimeTracker: JobChiefEngineer
  weight: 10
  startingGear: ChiefEngineerGear
  icon: "JobIconChiefEngineer"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - Command
  - External
  - ChiefEngineer
  - Atmospherics
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: ChiefEngineerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitChiefEngineer
    back: ClothingBackpackChiefEngineerFilled
    shoes: ClothingShoesColorBrown
    id: CEPDA
    ears: ClothingHeadsetCE
  innerClothingSkirt: ClothingUniformJumpskirtChiefEngineer
  satchel: ClothingBackpackSatchelChiefEngineerFilled
  duffelbag: ClothingBackpackDuffelChiefEngineerFilled
